version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_userway_container
    environment:
      MYSQL_ROOT_PASSWORD: userway_root_password
      MYSQL_DATABASE: userway_db
      MYSQL_USER: userway_username
      MYSQL_PASSWORD: userway_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  mysql_data:
